export const SWITCH_PLAY_STATUS = 'SWITCH_PLAY_STATUS'
export const CAN_PLAY = 'CAN_PLAY'
export const NEXT_SONG = 'NEXT_SONG'
export const FETCH_DATA = 'FETCH_DATA'
export const SWITCH_USER_TO_MAY = 'SWITCH_USER_TO_MAY'
